/**
 * Flags codegen — turns a live server's flag definitions into a typed
 * `Flags` schema augmentation so `vb.flags.isEnabled("typo")` becomes
 * a compile-time error.
 *
 * Output shape:
 *   export type FlagKey = "new_checkout" | "checkout_variant";
 *   export interface FlagTypes {
 *     new_checkout: boolean;
 *     checkout_variant: "control" | "treatment_a";
 *   }
 *   declare module "@vaultbase/sdk" {
 *     interface FlagSchema extends FlagTypes {}
 *   }
 *
 * Boolean flags produce `boolean`. String flags with named variations
 * narrow to the variation literal union when possible. Number/JSON
 * flags emit their TS type plain.
 */

interface FlagShape {
  key: string;
  type: "bool" | "string" | "number" | "json";
  variations: Array<{ name: string; value: unknown }>;
}

export async function fetchFlags(opts: { url: string; adminToken: string }): Promise<FlagShape[]> {
  const res = await fetch(`${opts.url.replace(/\/$/, "")}/api/admin/flags`, {
    headers: { Authorization: `Bearer ${opts.adminToken}` },
  });
  if (!res.ok) throw new Error(`fetch flags: ${res.status} ${res.statusText}`);
  const body = await res.json() as { data?: FlagShape[] };
  return body.data ?? [];
}

export function generateFlagTypes(flags: FlagShape[]): string {
  const lines: string[] = [
    "// AUTO-GENERATED by `vb-flags`. Do not edit by hand.",
    "// Re-run when flag definitions change.",
    "",
  ];
  if (flags.length === 0) {
    lines.push("export type FlagKey = never;");
    lines.push("export interface FlagTypes {}");
    return lines.join("\n") + "\n";
  }
  const keys = flags.map((f) => JSON.stringify(f.key)).join(" | ");
  lines.push(`export type FlagKey = ${keys};`);
  lines.push("");
  lines.push("export interface FlagTypes {");
  for (const f of flags) {
    const tsType = tsTypeFor(f);
    lines.push(`  ${quoteKey(f.key)}: ${tsType};`);
  }
  lines.push("}");
  lines.push("");
  lines.push('declare module "@vaultbase/sdk" {');
  lines.push("  interface FlagSchema extends FlagTypes {}");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function tsTypeFor(f: FlagShape): string {
  if (f.type === "bool") return "boolean";
  if (f.type === "number") return "number";
  if (f.type === "json") return "unknown";
  // string with named variations narrows to literal union
  const stringValues = f.variations
    .map((v) => v.value)
    .filter((x): x is string => typeof x === "string");
  if (stringValues.length === 0) return "string";
  return stringValues.map((v) => JSON.stringify(v)).join(" | ");
}

function quoteKey(key: string): string {
  return /^[a-zA-Z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
}
