/**
 * Schema-snapshot → TypeScript code generation.
 *
 * Input: the JSON shape returned by `GET /api/admin/migrations/snapshot` —
 * an array of collections with `{ name, type, fields, view_query, ...rules }`
 * where `fields` is a JSON-encoded array of `{ name, type, required, options }`
 * objects.
 *
 * Output: a `.ts` source file with one record / create / update interface
 * per collection plus a top-level `Schema` type.
 */

export interface SnapshotField {
  name: string;
  type: string;
  required?: boolean;
  system?: boolean;
  implicit?: boolean;
  collection?: string;
  options?: Record<string, unknown>;
  onCreate?: boolean;
  onUpdate?: boolean;
}

export interface SnapshotCollection {
  id?: string;
  name: string;
  type: "base" | "auth" | "view";
  fields: string | SnapshotField[];
  view_query?: string | null;
}

export interface SnapshotShape {
  collections: SnapshotCollection[];
  /** Optional flag to suppress writing `Update` types for view collections. */
}

export interface GenerateOptions {
  /** Header text — defaults to a do-not-edit banner. */
  header?: string;
}

const DEFAULT_HEADER = `// AUTO-GENERATED by \`vb-types\`. Do not edit.\n// Regenerate via:  npx vb-types --schema=./vaultbase-schema.json\n`;

/** Top-level entry point. */
export function generateTypes(snapshot: SnapshotShape, opts: GenerateOptions = {}): string {
  const header = opts.header ?? DEFAULT_HEADER;
  const parts: string[] = [header, ""];

  const interfaces: string[] = [];
  const schemaEntries: string[] = [];
  for (const col of snapshot.collections) {
    if (!isValidIdent(col.name)) continue;
    const fields = parseFields(col.fields);
    const baseName = pascal(col.name);
    const recordName = `${baseName}Record`;
    const createName = `${baseName}Create`;
    const updateName = `${baseName}Update`;

    interfaces.push(emitRecord(recordName, fields, col));
    if (col.type !== "view") {
      interfaces.push(emitCreate(createName, fields, col));
      interfaces.push(emitUpdate(updateName, createName));
    }

    if (col.type === "view") {
      schemaEntries.push(`  ${quoteKey(col.name)}: { record: ${recordName}; create: never; update: never };`);
    } else {
      schemaEntries.push(`  ${quoteKey(col.name)}: { record: ${recordName}; create: ${createName}; update: ${updateName} };`);
    }
  }

  parts.push(interfaces.join("\n\n"));
  parts.push("");
  parts.push("export type Schema = {");
  parts.push(schemaEntries.join("\n"));
  parts.push("};");
  parts.push("");
  return parts.join("\n");
}

function parseFields(raw: string | SnapshotField[]): SnapshotField[] {
  if (Array.isArray(raw)) return raw;
  try { return JSON.parse(raw) as SnapshotField[]; } catch { return []; }
}

function emitRecord(name: string, fields: SnapshotField[], col: SnapshotCollection): string {
  const lines: string[] = [`export interface ${name} {`];
  lines.push(`  id: string;`);
  lines.push(`  created: number;`);
  lines.push(`  updated: number;`);

  if (col.type === "auth") {
    lines.push(`  email: string;`);
    lines.push(`  verified: boolean;`);
  }

  for (const f of fields) {
    if (f.system) continue;
    if (f.type === "password") continue; // never on Record
    if (col.type === "auth" && (f.name === "email" || f.name === "password")) continue;
    const t = tsType(f, "read");
    const opt = f.required ? "" : "?";
    lines.push(`  ${quoteKey(f.name)}${opt}: ${t};`);
  }
  lines.push("}");
  return lines.join("\n");
}

function emitCreate(name: string, fields: SnapshotField[], col: SnapshotCollection): string {
  const lines: string[] = [`export interface ${name} {`];

  if (col.type === "auth") {
    lines.push(`  email: string;`);
    lines.push(`  password: string;`);
  }

  for (const f of fields) {
    if (f.system) continue;
    if (f.type === "autodate") continue;
    if (col.type === "auth" && (f.name === "email" || f.name === "password" || f.name === "verified")) continue;
    const t = tsType(f, "write");
    const opt = f.required ? "" : "?";
    lines.push(`  ${quoteKey(f.name)}${opt}: ${t};`);
  }
  lines.push("}");
  return lines.join("\n");
}

function emitUpdate(name: string, createName: string): string {
  return `export type ${name} = Partial<${createName}>;`;
}

function tsType(f: SnapshotField, mode: "read" | "write"): string {
  switch (f.type) {
    case "text":
    case "email":
    case "url":
    case "editor":
    case "date":
    case "relation":
      return "string";
    case "number":
      return "number";
    case "bool":
      return "boolean";
    case "autodate":
      return "number";
    case "json":
      return "unknown";
    case "geoPoint":
      return "{ lat: number; lng: number }";
    case "select": {
      const opts = (f.options ?? {}) as { values?: string[]; multiple?: boolean };
      const values = opts.values ?? [];
      const literals = values.length > 0
        ? values.map((v) => JSON.stringify(v)).join(" | ")
        : "string";
      return opts.multiple ? `(${literals})[]` : literals;
    }
    case "file": {
      const opts = (f.options ?? {}) as { multiple?: boolean };
      return opts.multiple ? "string[]" : "string";
    }
    case "password":
      return "string";
    default:
      return "unknown";
  }
}

function quoteKey(s: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(s) ? s : JSON.stringify(s);
}

function pascal(s: string): string {
  return s
    .split(/[^A-Za-z0-9]/)
    .filter(Boolean)
    .map((seg) => seg[0]!.toUpperCase() + seg.slice(1))
    .join("");
}

function isValidIdent(s: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]{0,62}$/.test(s);
}
